### ISSUE TITLE
Iterative processing of crashdump on low memory machines

### ISSUE THREAD

**Issue by jamesaimonetti** [archaelus/edump#3]
Hi Geoff,

Curious if you had suggestions for using edump to process large (14G) crashdumps on machines with less RAM.

In my specific case, I have a large-memory server that had a bug triggered where a single process got stuck and its message_queue has 2462553 messages (according to recon's erl_crashdump analyzer script).

The resulting crash dump is 14G on disk. Observer's crashdump_viewer taxes my laptop with 20G and crashes the VM when analyzing it (I even recompiled it to use 'compressed' in the ets:new/2), so I can't access much more than recon's summary. edump feels like it should be able to analyze the contents more efficiently but I can't seem to create the index file without blowing up memory too.

I'm assuming you've run into these large crash dumps before; any hints on how to process one this large?

**Comment by archaelus** [comment]
Wow, I have not checked in here in a while.

It is definitely the intention for edump to be useful for processing huge crash dump files (I got frustrated with crashdump_viewer choking on pretty tiny crashdumps). https://github.com/archaelus/edump/blob/master/src/edump_idx.erl#L251-L269 is where the index building happens - line by line is the algorithm, but I may have made some kind of mistake and leaked data that builds up as indexing proceeds?

Do you have a crashdump of edump exhausting memory when you try to index the file? That would be useful to see in order to figure out where the memory consumption is going.
